Algoritmo "Ex61"

//Faça um programa que crie e inicialize um array de 20 posições de inteiros -
// - com  0 para cada elemento. Imprima o vetor em seguida, indicando -
// - a posição e o valor na posição (um por linha).

Var

x: vetor[1..20] de inteiro  //Variável do tipo vetor
i: inteiro //Variável de repetição (Para - For)

Inicio

// Estrutura de repetição (Para- For)

para i de 1 ate 20 faça
     escreval("Posição[",i,"] = ", x[i])
fimpara




Fimalgoritmo