Algoritmo "ex88"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 2/6/2022
Var
// Seção de Declarações das variáveis 
palavra : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Entre com uma palavra: ")
leia(palavra)

palavra := Maiusc(palavra)

escreva("A palavra em caixa alta fica: ", palavra)

Fimalgoritmo