Algoritmo "ex18"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/5/2022
Var
// Seção de Declarações das variáveis 
n1, n2 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Entre com o n1: ")
leia(n1)

escreva("Entre com o n2: ")
leia(n2)

n1 := n1 + n2
n2 := n1 - n2
n1 := n1 - n2

escreval("N1: ", n1)

escreval("N2: ", n2)

Fimalgoritmo