Algoritmo "semome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2022
Var
// Seção de Declarações das variáveis 
A, B: inteiro
quociente: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Entra com valor A")
leia(A)
escreval

escreval("Entra com valor B")
leia(B)
escreval

quociente := A / B

escreval("O quociente é", quociente)

Fimalgoritmo