Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/05/2022
Var
// Seção de Declarações das variáveis 
A, B: inteiro
R: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Entra com valor A")
leia(A)
escreval

escreval("Entra com valor B")
leia(B)
escreval

R := A % B

escreval("O Resultado é", R)



Fimalgoritmo
