Algoritmo "ex43"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2022
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para num de 2 ate 100 faca
      se (num % 2 <> 1) entao
         escreval(num)
      fimse
 fimpara

Fimalgoritmo